# Generated by Django 5.2.14 on 2026-06-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ddcs_metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIHashtagInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_infos', to='ddcs_metadata.tiktokhashtag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIMusicInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_infos', to='ddcs_metadata.tiktokmusic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIUserInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('is_private', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_infos', to='ddcs_metadata.tiktokuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIUserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('following_count', models.PositiveIntegerField(blank=True, null=True)),
                ('follower_count', models.PositiveIntegerField(blank=True, null=True)),
                ('video_count', models.PositiveIntegerField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='ddcs_metadata.tiktokuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIVideoInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('region_code', models.CharField(blank=True, max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('voice_to_text', models.TextField(blank=True, null=True)),
                ('is_stem_verified', models.BooleanField(blank=True, null=True)),
                ('video_mention_list', models.JSONField(blank=True, null=True)),
                ('video_label', models.JSONField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_infos', to='ddcs_metadata.tiktokvideo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIVideoStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(blank=True, null=True)),
                ('like_count', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('share_count', models.PositiveIntegerField(blank=True, null=True)),
                ('favorites_count', models.PositiveIntegerField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='ddcs_metadata.tiktokvideo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
