# Generated by Django 5.2.14 on 2026-06-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata_research_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apihashtaginfos',
            options={'verbose_name': 'API Hashtag Infos', 'verbose_name_plural': 'API Hashtag Infos'},
        ),
        migrations.AlterModelOptions(
            name='apimusicinfos',
            options={'verbose_name': 'API Music Infos', 'verbose_name_plural': 'API Music Infos'},
        ),
        migrations.AlterModelOptions(
            name='apiuserinfos',
            options={'verbose_name': 'API User Infos', 'verbose_name_plural': 'API User Infos'},
        ),
        migrations.AlterModelOptions(
            name='apiuserstatistics',
            options={'verbose_name': 'API User Statistics', 'verbose_name_plural': 'API User Statistics'},
        ),
        migrations.AlterModelOptions(
            name='apivideoinfos',
            options={'verbose_name': 'API Video Infos', 'verbose_name_plural': 'API Video Infos'},
        ),
        migrations.AlterModelOptions(
            name='apivideostatistics',
            options={'verbose_name': 'API Video Statistics', 'verbose_name_plural': 'API Video Statistics'},
        ),
    ]
