# Generated by Django 5.2.14 on 2026-06-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata_research_api', '0002_alter_apihashtaginfos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apivideoinfos',
            name='effect_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apivideoinfos',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apivideoinfos',
            name='voice_to_text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
