# Generated by Django 5.2.17 on 2026-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0008_tiktokuser_tiktokuser_monitor_api_idx_and_more'),
        ('ddcs_metadata_research_api', '0003_apivideoinfos_effect_list_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apivideoinfos',
            index=models.Index(fields=['video', '-created_at'], name='apiinfos_vid_created_idx'),
        ),
    ]
