# Generated by Django 5.2.17 on 2026-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0011_remove_tiktokvideoclassification_image_paths_and_more'),
        ('ddcs_metadata_research_api', '0004_apivideoinfos_apiinfos_vid_created_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apivideoinfos',
            index=models.Index(fields=['create_time'], name='apiinfos_create_time_idx'),
        ),
    ]
