# Generated by Django 5.2.17 on 2026-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0011_remove_tiktokvideoclassification_image_paths_and_more'),
        ('ddcs_metadata_research_api', '0005_apivideoinfos_apiinfos_create_time_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apivideoinfos',
            name='apiinfos_create_time_idx',
        ),
        migrations.AddIndex(
            model_name='apivideoinfos',
            index=models.Index(fields=['create_time'], include=('video',), name='apiinfos_ctime_video_idx'),
        ),
    ]
