# Generated by Django 5.2.15 on 2026-06-24 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ddm_participation', '0002_alter_participant_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantReportStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('videos_seen_count_total', models.IntegerField(default=0)),
                ('seen_pol_video_ids', models.JSONField()),
                ('liked_pol_video_ids', models.JSONField()),
                ('followed_pol_users', models.JSONField()),
                ('party_counts', models.JSONField()),
                ('daily_party_counts', models.JSONField()),
                ('hashtags_by_pol_video', models.JSONField()),
                ('top_videos', models.JSONField(default=list)),
                ('party_hashtags', models.JSONField()),
                ('non_party_hashtags', models.JSONField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddm_participation.participant')),
            ],
        ),
    ]
