# Generated by Django 5.2.15 on 2026-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcs_reports", "0001_initial"),
        ("ddm_participation", "0002_alter_participant_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participantreportstatistics",
            options={"ordering": ("-generated_at",)},
        ),
        migrations.AddField(
            model_name="participantreportstatistics",
            name="behaviour_comparisons",
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name="participantreportstatistics",
            index=models.Index(
                fields=["participant", "-generated_at"],
                name="ddcs_report_partici_825666_idx",
            ),
        ),
    ]
