# Generated by Django 5.2.14 on 2026-06-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(choices=[('RESEARCH_API', 'Research API'), ('SCRAPER', 'Scraper'), ('DONATION', 'Donation'), ('IMPORT', 'Import')], max_length=24)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('monitor_api', models.BooleanField(default=False)),
                ('monitoring_priority_api', models.IntegerField(default=0)),
                ('api_last_monitored_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('id_tiktok', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TikTokMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(choices=[('RESEARCH_API', 'Research API'), ('SCRAPER', 'Scraper'), ('DONATION', 'Donation'), ('IMPORT', 'Import')], max_length=24)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('id_tiktok', models.BigIntegerField(db_index=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TikTokUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(choices=[('RESEARCH_API', 'Research API'), ('SCRAPER', 'Scraper'), ('DONATION', 'Donation'), ('IMPORT', 'Import')], max_length=24)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('monitor_api', models.BooleanField(default=False)),
                ('monitoring_priority_api', models.IntegerField(default=0)),
                ('api_last_monitored_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('id_tiktok', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'TikTok User',
                'verbose_name_plural': 'TikTok Users',
            },
        ),
        migrations.CreateModel(
            name='TikTokVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(choices=[('RESEARCH_API', 'Research API'), ('SCRAPER', 'Scraper'), ('DONATION', 'Donation'), ('IMPORT', 'Import')], max_length=24)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('id_tiktok', models.BigIntegerField(db_index=True, unique=True)),
                ('inferred_create_time', models.DateTimeField(blank=True, help_text='Create time as inferred from the TikTok ID.', null=True)),
                ('hashtags', models.ManyToManyField(blank=True, to='ddcs_metadata.tiktokhashtag')),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ddcs_metadata.tiktokmusic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ddcs_metadata.tiktokuser')),
            ],
            options={
                'verbose_name': 'TikTok Video',
                'verbose_name_plural': 'TikTok Videos',
            },
        ),
    ]
