# Generated by Django 5.2.14 on 2026-06-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiktokhashtag',
            options={'verbose_name': 'Hashtags', 'verbose_name_plural': 'Hashtags'},
        ),
        migrations.AlterModelOptions(
            name='tiktokmusic',
            options={'verbose_name': 'TikTok Music', 'verbose_name_plural': 'TikTok Music'},
        ),
    ]
