# Generated by Django 5.2.15 on 2026-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0002_alter_tiktokhashtag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAPIQueryTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('query_function', models.CharField(max_length=100)),
                ('query_parameters', models.JSONField()),
                ('query_result', models.JSONField(null=True)),
                ('query_status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('soft_time_limit_exceeded', 'Soft Time Limit Exceeded'), ('failed', 'Failed')], default='started', max_length=32)),
            ],
        ),
    ]
