# Generated by Django 5.2.15 on 2026-06-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0003_researchapiquerytracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchapiquerytracker',
            options={'verbose_name': 'Research API Query Tracker', 'verbose_name_plural': 'Research API Query Trackers'},
        ),
        migrations.AddField(
            model_name='researchapiquerytracker',
            name='query_exception_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchapiquerytracker',
            name='query_status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('soft_time_limit_exceeded', 'Soft Time Limit Exceeded'), ('failed', 'Failed'), ('partial_failure', 'Partial Failure')], default='started', max_length=32),
        ),
    ]
