# Generated by Django 5.2.15 on 2026-06-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0004_alter_researchapiquerytracker_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokUserAPISync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_date', models.DateField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_syncs', to='ddcs_metadata.tiktokuser')),
            ],
            options={
                'unique_together': {('user', 'synced_date')},
            },
        ),
    ]
