# Generated by Django 5.2.15 on 2026-07-02 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0005_tiktokuserapisync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokhashtag',
            name='api_last_monitored_at',
        ),
        migrations.RemoveField(
            model_name='tiktokuser',
            name='api_last_monitored_at',
        ),
        migrations.AlterField(
            model_name='researchapiquerytracker',
            name='query_status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('soft_time_limit_exceeded', 'Soft Time Limit Exceeded'), ('failed', 'Failed'), ('partial_failure', 'Partial Failure'), ('rate_limit_exceeded', 'Rate Limit Exceeded')], default='started', max_length=32),
        ),
        migrations.CreateModel(
            name='SyncAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(help_text='The day the API was queried for (not when the attempt ran).')),
                ('status', models.CharField(choices=[('success', 'Success'), ('rate_limited', 'Rate Limited'), ('timeout', 'Timeout'), ('api_error', 'Api Error'), ('unknown', 'Unknown')], max_length=16)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.ForeignKey(blank=True, help_text='Target when the item was queried as a keyword.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='ddcs_metadata.tiktokhashtag')),
                ('tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='ddcs_metadata.researchapiquerytracker')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='ddcs_metadata.tiktokuser')),
            ],
        ),
        migrations.DeleteModel(
            name='TikTokUserAPISync',
        ),
        migrations.AddIndex(
            model_name='syncattempt',
            index=models.Index(fields=['user', 'target_date'], name='ddcs_metada_user_id_58f055_idx'),
        ),
        migrations.AddIndex(
            model_name='syncattempt',
            index=models.Index(fields=['hashtag', 'target_date'], name='ddcs_metada_hashtag_2f29bd_idx'),
        ),
        migrations.AddIndex(
            model_name='syncattempt',
            index=models.Index(fields=['target_date', 'status'], name='ddcs_metada_target__364d1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hashtag__isnull', True), ('user__isnull', False)), models.Q(('hashtag__isnull', False), ('user__isnull', True)), _connector='OR'), name='syncattempt_has_exactly_one_target'),
        ),
    ]
