# Generated by Django 5.2.15 on 2026-08-10 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0006_remove_tiktokhashtag_api_last_monitored_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(choices=[('RESEARCH_API', 'Research API'), ('SCRAPER', 'Scraper'), ('DONATION', 'Donation'), ('IMPORT', 'Import')], max_length=24)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('monitor_api', models.BooleanField(default=False)),
                ('monitoring_priority_api', models.IntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='syncattempt',
            name='syncattempt_has_exactly_one_target',
        ),
        migrations.AlterField(
            model_name='syncattempt',
            name='hashtag',
            field=models.ForeignKey(blank=True, help_text='Target when the item was queried as a keyword (hashtag).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='ddcs_metadata.tiktokhashtag'),
        ),
        migrations.AddField(
            model_name='syncattempt',
            name='keyword',
            field=models.ForeignKey(blank=True, help_text='Target when the item was queried as a keyword.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='ddcs_metadata.keyword'),
        ),
        migrations.AddField(
            model_name='tiktokvideo',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='ddcs_metadata.keyword'),
        ),
        migrations.AddIndex(
            model_name='syncattempt',
            index=models.Index(fields=['keyword', 'target_date'], name='ddcs_metada_keyword_d6f23e_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hashtag__isnull', True), ('keyword__isnull', True), ('user__isnull', False)), models.Q(('hashtag__isnull', False), ('keyword__isnull', True), ('user__isnull', True)), models.Q(('hashtag__isnull', True), ('keyword__isnull', False), ('user__isnull', True)), _connector='OR'), name='syncattempt_has_exactly_one_target'),
        ),
    ]
