# Generated by Django 5.2.17 on 2026-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0007_keyword_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tiktokuser',
            index=models.Index(fields=['monitor_api'], name='tiktokuser_monitor_api_idx'),
        ),
        migrations.AddIndex(
            model_name='tiktokvideo',
            index=models.Index(fields=['-updated_at'], name='tiktokvideo_updated_at_idx'),
        ),
    ]
