# Generated by Django 5.2.17 on 2026-08-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0008_tiktokuser_tiktokuser_monitor_api_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokVideoClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_political', models.BooleanField(default=False)),
                ('stage1_rationale', models.TextField(blank=True)),
                ('entities', models.JSONField(blank=True, default=list, null=True)),
                ('keyword_matches', models.JSONField(blank=True, default=list, null=True)),
                ('classification_ts', models.DateTimeField(blank=True, null=True)),
                ('is_sentiment_positive', models.BooleanField(default=False)),
                ('is_sentiment_negative', models.BooleanField(default=False)),
                ('is_sentiment_neutral', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='ddcs_metadata.tiktokvideo')),
            ],
        ),
    ]
