# Generated by Django 5.2.17 on 2026-08-24 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0009_tiktokvideoclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='image_paths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='post_scrape_prediction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='scraped_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='video_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tiktokvideoclassification',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='ddcs_metadata.tiktokvideo'),
        ),
    ]
