# Generated by Django 5.2.17 on 2026-09-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0010_tiktokvideoclassification_image_paths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokvideoclassification',
            name='image_paths',
        ),
        migrations.RemoveField(
            model_name='tiktokvideoclassification',
            name='post_scrape_prediction',
        ),
        migrations.RemoveField(
            model_name='tiktokvideoclassification',
            name='video_path',
        ),
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='plausible_party',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='political_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='political_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiktokvideoclassification',
            name='prediction_scraped',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
