# Generated by Django 5.2.13 on 2026-04-25 17:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 7), ('section', 9), ('participation_section', 11), ('card_section', 15), ('logo_banner', 16), ('regular_page', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'hero', 'help_text': "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('_blank', 'New tab'), ('_self', 'Same tab')]}), 7: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('subtitle', 1), ('intro', 2), ('show_cta_button', 3), ('cta_button_label', 4), ('cta_button_link', 5), ('show_secondary_link', 3), ('secondary_link_label', 4), ('secondary_link', 5), ('secondary_link_target', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)", 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('anchor_id', 8), ('pre_title', 1), ('title', 1), ('content', 2)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'participation', 'help_text': "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)", 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('anchor_id', 10), ('pre_title', 1), ('title', 1), ('content', 2), ('step_1_title', 1), ('step_1_content', 2), ('step_2_title', 1), ('step_2_content', 2), ('step_3_title', 1), ('step_3_content', 2)]], {}), 12: ('wagtail.blocks.URLBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 1), ('source_name', 1), ('url', 12), ('include_image', 3), ('image_url', 5)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('anchor_id', 8), ('pre_title', 1), ('title', 1), ('cards', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[]], {}), 17: ('wagtail.blocks.StructBlock', [[('pre_title', 1), ('title', 1), ('content', 2)]], {})})),
                ('nav_links', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Takes precedence over URL if both are set', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': "Use this for links not accessible through 'page'", 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor on the target page, e.g. 'about' → page.url#about", 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('anchor_id', 3)]], {})}, help_text='Links to other pages to include in the navigation')),
                ('nav_anchors', wagtail.fields.StreamField([('anchor', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Must match the anchor_id set on the target section block'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('label', 1)]], {})}, help_text='Sections on this page to link in the navigation')),
            ],
            options={
                'verbose_name': 'Site Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_links', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Takes precedence over URL if both are set', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': "Use this for links not accessible through 'page'", 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor on the target page, e.g. 'about' → page.url#about", 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('anchor_id', 3)]], {})}, help_text='Links shown in the main navigation')),
                ('footer_pages', models.ManyToManyField(blank=True, help_text='Pages linked in the footer', related_name='in_footer', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navigation Settings',
            },
        ),
    ]
