# Generated by Django 5.2.15 on 2026-06-24 04:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 7), ('section', 14), ('participation_section', 16), ('card_section', 20), ('logo_banner', 21), ('regular_page', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'hero', 'help_text': "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('_blank', 'New tab'), ('_self', 'Same tab')]}), 7: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('subtitle', 1), ('intro', 2), ('show_cta_button', 3), ('cta_button_label', 4), ('cta_button_link', 5), ('show_secondary_link', 3), ('secondary_link_label', 4), ('secondary_link', 5), ('secondary_link_target', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)", 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'required': True}), 10: ('wagtail.blocks.StructBlock', [[('title', 9)]], {}), 11: ('wagtail.blocks.URLBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('link', 11), ('link_target', 6)]], {}), 13: ('wagtail.blocks.StreamBlock', [[('richtext', 2), ('subtitle', 10), ('button', 12)]], {'blank': True, 'use_json_field': True}), 14: ('wagtail.blocks.StructBlock', [[('anchor_id', 8), ('pre_title', 1), ('title', 1), ('body', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'participation', 'help_text': "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)", 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('anchor_id', 15), ('pre_title', 1), ('title', 1), ('content', 2), ('step_1_title', 1), ('step_1_content', 2), ('step_2_title', 1), ('step_2_content', 2), ('step_3_title', 1), ('step_3_content', 2)]], {}), 17: ('wagtail.blocks.URLBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 1), ('source_name', 1), ('url', 17), ('include_image', 3), ('image_url', 5)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('anchor_id', 8), ('pre_title', 1), ('title', 1), ('cards', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[]], {}), 22: ('wagtail.blocks.StructBlock', [[('pre_title', 1), ('title', 1), ('body', 13)]], {})}),
        ),
    ]
