# Generated by Django 5.2.15 on 2026-07-03 11:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_website', '0002_alter_sitepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 9), ('section', 16), ('participation_section', 18), ('card_section', 22), ('logo_banner', 23), ('regular_page', 24), ('public_plots', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'hero', 'help_text': "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('_blank', 'New tab'), ('_self', 'Same tab')]}), 9: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('subtitle', 1), ('intro', 2), ('intro_bottom', 3), ('include_public_plots', 4), ('show_cta_button', 5), ('cta_button_label', 6), ('cta_button_link', 7), ('show_secondary_link', 5), ('secondary_link_label', 6), ('secondary_link', 7), ('secondary_link_target', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)", 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('title', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'required': True}), 14: ('wagtail.blocks.StructBlock', [[('label', 11), ('link', 13), ('link_target', 8)]], {}), 15: ('wagtail.blocks.StreamBlock', [[('richtext', 2), ('subtitle', 12), ('button', 14)]], {'blank': True, 'use_json_field': True}), 16: ('wagtail.blocks.StructBlock', [[('anchor_id', 10), ('pre_title', 1), ('title', 1), ('body', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'participation', 'help_text': "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)", 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('anchor_id', 17), ('pre_title', 1), ('title', 1), ('content', 2), ('step_1_title', 1), ('step_1_content', 2), ('step_2_title', 1), ('step_2_content', 2), ('step_3_title', 1), ('step_3_content', 2)]], {}), 19: ('wagtail.blocks.URLBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('title', 1), ('source_name', 1), ('url', 19), ('include_image', 5), ('image_url', 7)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('anchor_id', 10), ('pre_title', 1), ('title', 1), ('cards', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[]], {}), 24: ('wagtail.blocks.StructBlock', [[('pre_title', 1), ('title', 1), ('body', 15)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'So oft posten die Parteien im Vorfeld der Wahlen auf TikTok:', 'required': False}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Hilf uns zu verstehen, welche Inhalte die Bevölkerung tatsächlich erreichen!', 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('anchor_id', 10), ('text_above', 25), ('text_below', 26)]], {})}),
        ),
    ]
