# Generated by Django 5.2.17 on 2026-08-25 15:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcs_website", "0003_alter_sitepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 10),
                    ("section", 17),
                    ("participation_section", 19),
                    ("card_section", 23),
                    ("logo_banner", 24),
                    ("regular_page", 25),
                    ("public_plots", 28),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "hero",
                            "help_text": "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)",
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    5: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("_blank", "New tab"), ("_self", "Same tab")]},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Show TikTok, Instagram, and newsletter links at the end of the hero",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("subtitle", 1),
                                ("intro", 2),
                                ("intro_bottom", 3),
                                ("include_public_plots", 4),
                                ("show_cta_button", 5),
                                ("cta_button_label", 6),
                                ("cta_button_link", 7),
                                ("show_secondary_link", 5),
                                ("secondary_link_label", 6),
                                ("secondary_link", 7),
                                ("secondary_link_target", 8),
                                ("show_follow_banner", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)",
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    13: ("wagtail.blocks.StructBlock", [[("title", 12)]], {}),
                    14: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 12), ("link", 14), ("link_target", 8)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [[("richtext", 2), ("subtitle", 13), ("button", 15)]],
                        {"blank": True, "use_json_field": True},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 11),
                                ("pre_title", 1),
                                ("title", 1),
                                ("body", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "participation",
                            "help_text": "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 18),
                                ("pre_title", 1),
                                ("title", 1),
                                ("content", 2),
                                ("step_1_title", 1),
                                ("step_1_content", 2),
                                ("step_2_title", 1),
                                ("step_2_content", 2),
                                ("step_3_title", 1),
                                ("step_3_content", 2),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.URLBlock", (), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("source_name", 1),
                                ("url", 20),
                                ("include_image", 5),
                                ("image_url", 7),
                            ]
                        ],
                        {},
                    ),
                    22: ("wagtail.blocks.ListBlock", (21,), {}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 11),
                                ("pre_title", 1),
                                ("title", 1),
                                ("cards", 22),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.StructBlock", [[]], {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("pre_title", 1), ("title", 1), ("body", 16)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "So oft posten die Parteien im Vorfeld der Wahlen auf TikTok:",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Hilf uns zu verstehen, welche Inhalte die Bevölkerung tatsächlich erreichen!",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id", 11), ("text_above", 26), ("text_below", 27)]],
                        {},
                    ),
                },
            ),
        ),
    ]
