# Generated by Django 5.2.17 on 2026-08-25 15:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcs_website", "0004_hero_show_follow_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 12),
                    ("section", 19),
                    ("participation_section", 21),
                    ("card_section", 25),
                    ("logo_banner", 26),
                    ("regular_page", 27),
                    ("public_plots", 30),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "hero",
                            "help_text": "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)",
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Show the CTA button at the bottom of the hero (after intro / plots)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Also show the same CTA button directly under the subtitle",
                            "required": False,
                        },
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    9: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("_blank", "New tab"), ("_self", "Same tab")]},
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Show TikTok, Instagram, and newsletter links at the end of the hero",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("subtitle", 1),
                                ("intro", 2),
                                ("intro_bottom", 3),
                                ("include_public_plots", 4),
                                ("show_cta_button", 5),
                                ("show_cta_under_subtitle", 6),
                                ("cta_button_label", 7),
                                ("cta_button_link", 8),
                                ("show_secondary_link", 9),
                                ("secondary_link_label", 7),
                                ("secondary_link", 8),
                                ("secondary_link_target", 10),
                                ("show_follow_banner", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)",
                            "required": False,
                        },
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    15: ("wagtail.blocks.StructBlock", [[("title", 14)]], {}),
                    16: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 14), ("link", 16), ("link_target", 10)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [[("richtext", 2), ("subtitle", 15), ("button", 17)]],
                        {"blank": True, "use_json_field": True},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 13),
                                ("pre_title", 1),
                                ("title", 1),
                                ("body", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "participation",
                            "help_text": "Html ID used to link section (e.g. 'about' is accessible as: dfdw.de#about)",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 20),
                                ("pre_title", 1),
                                ("title", 1),
                                ("content", 2),
                                ("step_1_title", 1),
                                ("step_1_content", 2),
                                ("step_2_title", 1),
                                ("step_2_content", 2),
                                ("step_3_title", 1),
                                ("step_3_content", 2),
                            ]
                        ],
                        {},
                    ),
                    22: ("wagtail.blocks.URLBlock", (), {}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("source_name", 1),
                                ("url", 22),
                                ("include_image", 9),
                                ("image_url", 8),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 13),
                                ("pre_title", 1),
                                ("title", 1),
                                ("cards", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.StructBlock", [[]], {}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("pre_title", 1), ("title", 1), ("body", 18)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "So oft posten die Parteien im Vorfeld der Wahlen auf TikTok:",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Hilf uns zu verstehen, welche Inhalte die Bevölkerung tatsächlich erreichen!",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id", 13), ("text_above", 28), ("text_below", 29)]],
                        {},
                    ),
                },
            ),
        ),
    ]
