# Generated by Django 5.2.17 on 2026-10-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ddcs_metadata', '0011_remove_tiktokvideoclassification_image_paths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfosScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('video_mention_list', models.JSONField(blank=True, null=True)),
                ('effect_list', models.JSONField(blank=True, null=True)),
                ('location_created', models.CharField(blank=True, max_length=255)),
                ('text_language', models.CharField(blank=True, max_length=255)),
                ('category_type', models.IntegerField(blank=True, null=True)),
                ('original_item', models.BooleanField(blank=True, null=True)),
                ('official_item', models.BooleanField(blank=True, null=True)),
                ('private_item', models.BooleanField(blank=True, null=True)),
                ('is_ad', models.BooleanField(blank=True, null=True)),
                ('diversification_labels', models.JSONField(blank=True, null=True)),
                ('diversification_id', models.BigIntegerField(blank=True, null=True)),
                ('is_aigc', models.BooleanField(blank=True, null=True)),
                ('aigc_description', models.TextField(blank=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_infos', to='ddcs_metadata.tiktokvideo')),
            ],
            options={
                'verbose_name': 'Scraped Video Infos',
                'verbose_name_plural': 'Scraped Video Infos',
            },
        ),
        migrations.CreateModel(
            name='VideoStatisticsScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(blank=True, null=True)),
                ('like_count', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('share_count', models.PositiveIntegerField(blank=True, null=True)),
                ('favorites_count', models.PositiveIntegerField(blank=True, null=True)),
                ('repost_count', models.PositiveIntegerField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_statistics', to='ddcs_metadata.tiktokvideo')),
            ],
            options={
                'verbose_name': 'Scraped Video Statistics',
                'verbose_name_plural': 'Scraped Video Statistics',
            },
        ),
        migrations.CreateModel(
            name='ScrapeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inferred_create_time', models.DateTimeField(help_text="Publish time inferred from the video's TikTok ID. Newest targets are scraped first.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('unavailable', 'Unavailable'), ('covered_by_api', 'Covered By Api'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_type', models.CharField(blank=True, max_length=255)),
                ('last_error_msg', models.TextField(blank=True)),
                ('tiktok_status_code', models.IntegerField(blank=True, help_text='statusCode TikTok returned in place of the video data.', null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_target', to='ddcs_metadata.tiktokvideo')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-inferred_create_time'], name='scrapetarget_queue_idx')],
            },
        ),
    ]
