# Generated by Django 5.2.17 on 2026-10-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfosscraped',
            name='caption_is_auto_generated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoinfosscraped',
            name='caption_language',
            field=models.CharField(blank=True, help_text='TikTok\'s language tag of the caption, e.g. "deu-DE".', max_length=32),
        ),
        migrations.AddField(
            model_name='videoinfosscraped',
            name='caption_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('none_available', 'None Available'), ('fetched', 'Fetched'), ('failed', 'Failed')], default='not_requested', max_length=16),
        ),
        migrations.AddField(
            model_name='videoinfosscraped',
            name='caption_vtt',
            field=models.TextField(blank=True, help_text='The WebVTT caption file as downloaded (with timestamps).'),
        ),
        migrations.AddField(
            model_name='videoinfosscraped',
            name='voice_to_text',
            field=models.TextField(blank=True),
        ),
    ]
