# Generated by Django 5.2.17 on 2026-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0011_remove_tiktokvideoclassification_image_paths_and_more'),
        ('ddcs_metadata_scraper', '0002_videoinfosscraped_caption_is_auto_generated_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scrapetarget',
            name='scrapetarget_queue_idx',
        ),
        migrations.RemoveField(
            model_name='scrapetarget',
            name='inferred_create_time',
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='last_watched_at',
            field=models.DateTimeField(blank=True, help_text='Most recent view of the video within the watch window.', null=True),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of donations whose watch history contains the video within the watch window.'),
        ),
        migrations.AddIndex(
            model_name='scrapetarget',
            index=models.Index(fields=['status', '-occurrence_count', '-last_watched_at'], name='scrapetarget_queue_idx'),
        ),
    ]
