# Generated by Django 5.2.17 on 2026-10-07 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata_scraper', '0003_remove_scrapetarget_scrapetarget_queue_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapetarget',
            options={'permissions': [('sync_scrape_targets', 'Can claim scrape targets and submit scraped results')]},
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='API account that claimed the target (empty: built-in scraper).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='claimed_by_label',
            field=models.CharField(blank=True, help_text='Name the scraper gave itself when claiming (e.g. its host). Not verified.', max_length=100),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='claimed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
