# Generated by Django 5.2.17 on 2026-10-09 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_metadata', '0011_remove_tiktokvideoclassification_image_paths_and_more'),
        ('ddcs_metadata_scraper', '0004_scrapetarget_claims'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scrapetarget',
            index=models.Index(condition=models.Q(('last_watched_at__isnull', False), ('status', 'pending')), fields=['-last_watched_at', 'id'], name='scrapetarget_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapetarget',
            index=models.Index(condition=models.Q(('last_watched_at__isnull', False), ('status', 'failed')), fields=['-last_watched_at', 'id'], name='scrapetarget_failed_idx'),
        ),
    ]
