# Generated by Django 5.2.13 on 2026-04-22 15:30

import django.utils.timezone
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=255, unique=True)),
                ('access_token', encrypted_fields.fields.EncryptedTextField(max_length=255)),
                ('access_token_expires_at', models.DateTimeField(null=True)),
                ('refresh_token', encrypted_fields.fields.EncryptedTextField(max_length=255)),
                ('refresh_token_expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_type', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TikTokDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=255)),
                ('request_id', models.BigIntegerField(help_text='ID of data request as provided by TikTok', unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_polled', models.DateTimeField(null=True)),
                ('status', models.CharField(default='not polled', max_length=20)),
                ('download_attempted', models.BooleanField(default=False)),
                ('download_succeeded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
