# Generated by Django 5.2.17 on 2026-08-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_portability', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokdatarequest',
            name='open_id',
        ),
        migrations.AddField(
            model_name='tiktokdatarequest',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_requests', to='ddcs_portability.tiktokconnection'),
        ),
        migrations.AlterField(
            model_name='tiktokdatarequest',
            name='status',
            field=models.CharField(choices=[('not polled', 'not polled'), ('pending', 'pending'), ('downloading', 'ready to download'), ('downloaded', 'downloaded'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='not polled', max_length=20),
        ),
    ]
