# Generated by Django 5.2.17 on 2026-09-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_portability', '0002_remove_tiktokdatarequest_open_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokdatarequest',
            name='status',
            field=models.CharField(choices=[('not polled', 'not polled'), ('pending', 'pending'), ('downloading', 'ready to download'), ('downloaded', 'downloaded'), ('failed', 'failed'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='not polled', max_length=20),
        ),
    ]
