# Generated by Django 5.2.17 on 2026-09-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_portability', '0003_alter_tiktokdatarequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokconnection',
            name='project_slug',
            field=models.SlugField(default='', max_length=8),
        ),
    ]
