# Generated by Django 5.2.17 on 2026-09-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcs_portability', '0004_tiktokconnection_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokconnection',
            name='project_slug',
            field=models.SlugField(default=''),
        ),
    ]
